version: "3.9"

services:
  db:
    image: postgres:17
    container_name: manejo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Manejo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/manejo_seed.sql:/docker-entrypoint-initdb.d/manejo_seed.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manejo_web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/Manejo?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
